# Generated by Django 5.1 on 2024-08-31 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autohoulex', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Object',
            new_name='Orders',
        ),
    ]
