# Generated by Django 5.1 on 2024-08-31 19:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autohoulex', '0002_rename_object_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Enter the current date'),
            preserve_default=False,
        ),
    ]
