# Generated by Django 5.1 on 2024-08-31 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autohoulex', '0003_orders_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make',
            name='name',
            field=models.CharField(help_text='Enter the car manufacturer (e.g. Toyota, Ford)', max_length=255),
        ),
        migrations.AlterField(
            model_name='model',
            name='make',
            field=models.ForeignKey(help_text='Select the car make', on_delete=django.db.models.deletion.CASCADE, related_name='models', to='autohoulex.make'),
        ),
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(help_text='Enter the car model (e.g. Corolla, Civic)', max_length=255),
        ),
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.IntegerField(help_text='Enter the manufacturing year (e.g. 2020)'),
        ),
    ]
