# Generated by Django 5.1 on 2024-09-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autohoulex', '0004_alter_make_name_alter_model_make_alter_model_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='PB', max_length=2),
        ),
    ]
