# Generated by Django 5.1 on 2024-09-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autohoulex', '0005_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
