# Generated by Django 5.1 on 2024-09-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autohoulex', '0006_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='condition',
            field=models.BooleanField(default=False),
        ),
    ]
