# Generated by Django 5.1 on 2024-09-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autohoulex', '0008_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='operable',
            field=models.CharField(choices=[('yes', 'Non'), ('no', 'NO')], default='yes', max_length=10),
        ),
    ]
