# Generated by Django 5.1 on 2024-09-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autohoulex', '0009_orders_operable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='operable',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'NO')], default='yes', max_length=10),
        ),
    ]
